apiVersion: v1
kind: Service
metadata:
  name: elasticsearchheadless
spec:
  selector:
    app: elasticsearch
  clusterIP: None
  ports:
    - port: 9200
      name: es-node1
    - port: 9300
      name: es-node2